---
title: "abnj_explore"
author: "Millie Chapman"
date: "6/22/2020"
output: github_document
---

```{r}
library(tidyverse)
library(bbnj)
#install.packages("prioritizr")
#devtools::install_github("ecoquants/bbnj")

```

```{r}
# list bbnj datasets in RStudio:
data(package="bbnj")

# list raster layers within stacks (s_*)
names(s_fish_gfw)
```

```{r}
names(s_bio_gmbi)
```

```{r}
# get rasters from stacks
profit_fishing <- raster(s_fish_gfw, "mean_scaled_profits_with_subsidies") %>% 
  gap_fill_raster()
nspp_tunas     <- raster(s_bio_gmbi, "nspp_tunas.n.billfishes")
nspp_sharks    <- raster(s_bio_gmbi, "nspp_sharks")

# stack wanted rasters for later cropping
s <- stack(profit_fishing, nspp_tunas, nspp_sharks)
names(s) <- c("profit_fishing", "nspp_tunas", "nspp_sharks")
```


```{r}
plot(nspp_tunas)
```

```{r}
r_pu_id
data("r_pu_id")
```

```{r}
# show planning unit id raster
plot(r_pu_id, col = cols, main="pu_id")
```

```{r}
r_pu_area <- area(r_pu_id) %>%  # in km2
  mask(r_pu_id)

plot(r_pu_area, col = cols, main="pu_area (km2)")
A <- cellStats(r_pu_area, "sum")
r_pu_areas <- r_pu_area / A
#cellStats(r_pu_areas, "sum") # 1

plot(r_pu_areas, col = cols, main="pu_areas (sums to 1)")
```

```{r}
r_nspp_all <- raster(s_bio_gmbi, "nspp_all")
plot(r_nspp_all, col = cols, main="nspp, all taxa")
```

```{r}
r_nspp_all_as <- rescale_raster(r_nspp_all, multiply_area=T) # "bio_nspp"

plot(r_nspp_all_as, col = cols, main="nspp, all taxa, area scaled")
```

```{r}
grps_nspp <- names(s_bio_gmbi) %>% 
  str_subset("^nspp_") %>% 
  str_subset("_all$", negate=T)
s_bio_nspp_grps <- raster::subset(s_bio_gmbi, grps_nspp)

names(s_bio_nspp_grps) <- names(s_bio_nspp_grps) %>% 
  str_replace("nspp_", "")
plot(s_bio_nspp_grps, col = cols)
```

```{r}
plot(r_phys_seamounts, col = cols, main="r_phys_seamounts")
plot(s_phys_scapes, col = cols)
names(s_fish_gfw)
```

```{r}
plot(s_fish_gfw, col = cols)
```

```{r}
r_fish_gfw.profit <- raster(s_fish_gfw, "mean_scaled_profits") %>% 
  gap_fill_raster()
r_fish_gfw.profit.subsidies <- raster(s_fish_gfw, "mean_scaled_profits_with_subsidies") %>% 
  gap_fill_raster()

plot(r_fish_gfw.profit.subsidies, col=cols, main="r_gfw_profit.subsidies")
```

```{r}
r_fish_gfw.profit.subsidies_inv <- rescale_raster(r_fish_gfw.profit.subsidies, inverse=T) #, log=T)

hist(r_fish_gfw.profit.subsidies, main="r_gfw_profit.subsidies")
```

```{r}
p01_features <- stack(
  r_nspp_all_as,
  r_rls_all_as,
  rescale_raster(r_phys_seamounts),
  rescale_raster(r_phys_vents),
  rescale_stack(s_phys_scapes))
names(p01_features) <- c(
  "bio_nspp", 
  "bio_rls",
  "phys_seamounts",
  "phys_vents",
  glue("phys_scape{1:11}"))

# hist(r_nspp_all_as); hist(r_rls_all_as); hist(rescale_raster(r_phys_seamounts))

p01_sum <- raster::stackApply(p01_features, rep(1,nlayers(p01_features)), sum) %>% 
  mask(r_pu_id)
plot(p01_sum, col=cols)
```

```{r}
install.packages("/Library/gurobi811/mac64/R/gurobi_8.1-1_R_3.5.0.tar", repos = NULL, type = 'binary')
install.packages('slam')
```

```{r}
source('mip.R')
```

